### ISSUE TITLE
Decide on a name

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#1]
Working title was:

> This month in civic tech

**Comment by henare** [comment]
One from lunch:

> OpenAustralia Foundation Civic Tech Monthly

Has who runs it, where it's from geographically, what it's about, and how often you get it.

**Comment by henare** [comment]
Hmm, that could suggest it's "OpenAustralia Civic Tech" rather than general civic tech.

**Comment by equivalentideas** [comment]
I think just Civic Tech Monthly and it's from the OpenAustralia Foundation.

**Comment by henare** [comment]
I like that. Any other thoughts @openaustralia/team-oaf?

**Comment by kat** [comment]
:+1:  Either way round sounds fine to me. Also the design principles may influence this decision.

**Comment by henare** [comment]
It is so.
