### ISSUE TITLE
Include inspiration in the readme

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#10]
For recognition and also to remind us of the things we like.

Extracted from https://github.com/openaustralia/newsletter/issues/2#issuecomment-71784473

> We like:
> - Opening Parliament Newsbrief, e.g. http://blog.openingparliament.org/post/105548748873/openparl-newsbrief-december-18-2014#more
> - Web Directions http://www.webdirections.org/newsletter/

**Comment by equivalentideas** [comment]
Nieman Lab updates http://www.niemanlab.org/subscribe/
