### ISSUE TITLE
A massive week for They Vote For You

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#105]
Australia got a new Prime Minister this week—and as the media detailed the step by step drama, tens of thousands of people visited They Vote For You to see how the players had actually voted in Parliament.

Over 30,000 people have visited They Vote For You since the leadership challenge was announced. This over three times as many people as on the project’s launch day when it featured prominently in the Guardian Australia.

In a week of so many words, it's fantastic to see people looking for some real information about what MPs do in Parliament.

As it says on They Vote For You:

> Forget what politicians say. What truly matters is what they do. And what they do is vote, to write our laws which affect us all.

Henare went on FBi Radio’s Backchat on Saturday morning to talk about the project and why people are looking for the kind of information that They Vote For You provides. 

https://soundcloud.com/backchat-on-fbi/how-do-parliamentarians-really-vote-when-theyvote4you

**Comment by henare** [comment]
:+1: It'd be really nice if we could turn this into a blog post then link to that from the newsletter.
