### ISSUE TITLE
New York Senate Site Relaunch

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#127]
["New York Senate Site Relaunches With “Listening” Features"](http://civichall.org/civicist/new-york-senate-site-relaunches-with-listening-features/).

[This](http://www.nysenate.gov/) is one of the first legislative sites I've seen designed with people in mind, which is great. At first glance it also looks like a great site but if you dig a bit further you see it's just a good first effort (clicking "find your senator" gives you a login window, the issues search is a bit crap, "Senators Talking About this Issue" just takes to you to the profile page, etc.).

**Comment by equivalentideas** [comment]
Great starting point. Seems like there's a lot of stuff 'coming soon', http://www.nysenate.gov/coming-soon .

Nice item for the newsletter cause it gives people another example to compare their local sites too.
