### ISSUE TITLE
There's a hackathon to help refugees in Sydney!

### ISSUE THREAD

**Issue by JasonThomasData** [openaustralia/newsletter#129]
There's a hackathon to help refugees in Sydney!
Nuff said.

https://www.eventbrite.com.au/e/techfugees-australia-hackathon-tickets-19351828841?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&aff=esfb&utm-source=fb&utm-term=listing

**Comment by henare** [comment]
Yes it is. I'll update the title :)
