### ISSUE TITLE
Dataviz, data journalism storytelling event in Melbourne

### ISSUE THREAD

**Issue by JasonThomasData** [openaustralia/newsletter#130]
Hoping the newsletter comes out first.

There's a data expedition day in Melbourne, November 15.
Join a group to find data, explore and visualise the result.

https://register.canbook.me/data-expedition

**Comment by henare** [comment]
Looks like a great suggestion, thanks @JasonThomasData!

> Hoping the newsletter comes out first.

Alas, the newsletter is published on the Thursday before the pub meet so this will miss the cut :(
