### ISSUE TITLE
There’s something wrong with Andrew Wilkie’s voting record!

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#131]
https://www.openaustraliafoundation.org.au/2015/11/05/they-vote-for-you-theres-something-wrong-with-andrew-wilkies-voting-record/

**Comment by henare** [comment]
:+1:

**Comment by henare** [comment]
And https://www.openaustraliafoundation.org.au/2015/11/13/they-vote-for-you-join-our-summer-working-bee/
