### ISSUE TITLE
Add a note about contributing after the signup link in README.md

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#15]
We should direct people to issues

**Comment by henare** [comment]
Good call :+1:

**Comment by equivalentideas** [comment]
We'll do this once https://github.com/openaustralia/newsletter/pull/9 is merged

**Comment by equivalentideas** [comment]
closed by https://github.com/openaustralia/newsletter/commit/5044336a8e333adefb55fbb1069c5b868b0887a2
