### ISSUE TITLE
[ITEM] Perc, @otherchirps search interface for pecuniary interest docs

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#17]
http://percs.otherchirps.net/?query=development

Evolving from last months #nswvotes meetup, Chris Nilsson has whipped up a way to search the text in previous very inaccessible 2013-2014 NSW Legislative Assembly Pecuniary Interest Disclosures.

**Comment by henare** [comment]
:+1: love it.

While :fries: are good, I think you mean @otherchirps :smile:

**Comment by equivalentideas** [comment]
lol yes.

**Comment by equivalentideas** [comment]
Now on github https://github.com/otherchirps/percs
