### ISSUE TITLE
[ITEM] Announcement of digital transformation office

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/newsletter#20]
Worth saying that it's been announced and it's important for OAF and the civic tech community to help make it a good thing
- http://www.theregister.co.uk/2015/01/28/turnbulls_digital_transformation_office_has_no_plan_but_awesome_power/
- https://www.pm.gov.au/media/2015-01-23/establishment-digital-transformation-office
- http://www.malcolmturnbull.com.au/policy-faqs/faqs-the-digital-transformation-office
- http://www.theaustralian.com.au/technology/communications-minister-malcolm-turnbull-to-run-digital-transformation-office/story-e6frgakx-1227194892674

etc..

**Comment by equivalentideas** [comment]
Good call. Lots of people missed this.
