### ISSUE TITLE
[ITEM] Cuttlefish is now an official Poplus component

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/newsletter#22]
See:
- http://poplus.org/
- http://poplus.org/posts/cuttlefish/
- http://poplus.org/components/examples/#cuttlefish
- http://poplus.org/posts/email-is-your-secret-weapon/

**Comment by henare** [comment]
Hells yeah :guitar:

**Comment by equivalentideas** [comment]
As noted at the cafe, people interest in this might like to join the Poplus maillist http://poplus.org/get-involved/
