### ISSUE TITLE
[ITEM] Open Data Day event by @codeforaustralia in Sydney

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#24]
http://www.eventbrite.com.au/e/international-open-data-day-sydney-tickets-15462067460

**Comment by maxious** [comment]
There's some other Open Data Day things going on (we'll try to update this blog post as they come in) http://au.okfn.org/2015/02/10/australian-activities-on-international-open-data-day-21-february/

**Comment by equivalentideas** [comment]
Maybe you should contribute an item @maxious :stuck_out_tongue_winking_eye:
