### ISSUE TITLE
[ITEM] 3 ways to keep They Vote For You tickety boo

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#27]
https://www.openaustraliafoundation.org.au/2015/01/30/3-ways-to-keep-they-vote-for-you-tickety-boo

A big shout out to @MicaelaMicaela for her great work on They Vote For You and also some direction for kicking things off in 2015.

**Comment by henare** [comment]
:purple_heart: :green_heart: :yellow_heart: :blue_heart:
