### ISSUE TITLE
[ITEM] Git resources

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#29]
http://www.git-tower.com/learn/

Contributing through Git is an important skill for people working on civic tech and open source—but it ain't that easy to learn and it's not always clear where to start. In fact, I stole @henare 's first day at an oaf hackfest so he could teach me git a few years ago. Here are some resources for different learning styles on how to get started.

**Comment by henare** [comment]
GitHub has links to [heaps of great resources](https://help.github.com/articles/good-resources-for-learning-git-and-github/).

**Comment by equivalentideas** [comment]
@henare nice one. I think linking to both could be good, as they're quite different styles—suite different people.

**Comment by henare** [comment]
I think we should pick things we've personally found useful. There are plenty of resources out there that people can Google but the good stuff about newsletters is the personal recommendation aspect :books: 

What do you think?

**Comment by equivalentideas** [comment]
That's a nice idea.

I did find git-tower massively useful for a few years getting started, I also like the interactive resources https://www.codeschool.com/courses/try-git

What about you?

**Comment by henare** [comment]
:neckbeard: I just read binary directly and so I have no need for documentation :neckbeard:
