### ISSUE TITLE
Add newsletter sign up form to blog

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#3]

**Comment by equivalentideas** [comment]
We can do this with the [mailchimp wp plugin](https://wordpress.org/plugins/mailchimp-for-wp/)

**Comment by equivalentideas** [comment]
done. See the righthand column https://www.openaustraliafoundation.org.au/

**Comment by kat** [comment]
You've added a signup to the newsletter on the blog, not a link to the blog in the newsletter. Since the problem was no one goes back to the blog once they've been there to read one thing, I'm not sure sending them to the newsletter, which is not specifically geared to sharing our updates is the right solution.

**Comment by equivalentideas** [comment]
ah right, sorry I interpreted this as 'add link to signup (to the newsletter) to blog' :)

Does this actually mean 'add a link into the newsletter template to a signup form to get emails about blog updates specifically'?

If that's the case, I think that the things that appear in the blog should end up in the newsletter if they are relevant to these people, so they shouldn't need to multiple subscriptions.

**Comment by henare** [comment]
> ah right, sorry I interpreted this as 'add link to signup (to the newsletter) to blog' :)

I think that's correct too.

@kat are you sure you weren't thinking of https://github.com/openaustralia/oaf/issues/191 ? This repo is specifically for the newsletter.

**Comment by kat** [comment]
yes, @henare I'm sure I'm sure  and yes openaustralia/oaf#191 still stands :-) and @equivalentideas that's great yes. SGTM.

**Comment by equivalentideas** [comment]
nice. I just updated the name to clarify this one. Closing.
