### ISSUE TITLE
[ITEM] The Poplus Component Integration toolkit

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#32]
An [early version](https://github.com/openpolis/poplus-pci) is available, [more details](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/poplus/NEpLV_omCaI/VlqbSG-f9SAJ) on the Poplus list.

**Comment by equivalentideas** [comment]
If there's anymore text you'd like to have with this in the newsletter, best to add it now while it's on your mind. That will give us an easier time when publishing :)
