### ISSUE TITLE
interview civic techies in London

### ISSUE THREAD

**Issue by kat** [openaustralia/newsletter#34]
@equivalentideas While in London, interview Tom Steinberg and civic techies you meet there. Maybe @matthewlandauer and @henare have suggestions too.

**Comment by henare** [comment]
Great idea. There's so many interesting people over there, I've been mentioning a few to @equivalentideas as people he might like to visit.

**Comment by equivalentideas** [comment]
Closing this as it didn't happen for lack of time :)
