### ISSUE TITLE
[ITEM] NSW Pecuniary Interest Register transcribing

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#38]
http://www.theguardian.com/australia-news/datablog/ng-interactive/2015/mar/09/help-us-investigate-the-register-of-interests-political-gifts-and-investments-in-nsw

**Comment by equivalentideas** [comment]
Lovely. @henare what is interesting about this? (text please) :)

**Comment by kat** [comment]
How about:

Nick Evershed and The Guardian's datablog are enticing their NSW readers to [help investigate the state’s register of pecuniary interests](http://www.theguardian.com/australia-news/datablog/ng-interactive/2015/mar/09/help-us-investigate-the-register-of-interests-political-gifts-and-investments-in-nsw_.). They’re using technology to crowdsource transcriptions to change the form this data is available to the public. By transcribing all these entries, together, we create a new data set, one which is open to search, scrutiny and analysis. It’s one of those situations where neither parliament nor politicians have previously shown any interest in making this data accessible and usable. 

Here citizens and journalists can collectively transform that information into structured usable data which fundamentally changes the power balance. 

It’s a blend of political story, instruction, motivation and invitation to act. 

I’d be great to follow up and ask Nick & Todd more about how this project came about, their design process, and results they turned up next time.

**Comment by henare** [comment]
It's a bit late now - sorry! - but it would've been nice to incorporate the fact that this was borne out of the pub meet.

**Comment by mlandauer** [comment]
@henare that's my fault. It was in @equivalentideas original draft and then i merged in Kat's wording but lost that. I'll add something back

**Comment by henare** [comment]
Oh awesome, thanks @mlandauer. Sorry I didn't pick it up earlier.
