### ISSUE TITLE
Announce this on the Google Group

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#4]
- Ask people to sign up
- Tell them about using issues to submit items
- Point people to #1

**Comment by henare** [comment]
@equivalentideas convinced me that signing people up automatically would be a :frowning: move.

**Comment by equivalentideas** [comment]
draft text:

> Hey everyone, we've got a big announcement. We're launch a new newsletter for people interested in the development of technology to enable civic change—people like you. The working title: Civic Tech Monthly.
> 
> Subscribe here http://eepurl.com/bcE0DX
> 
> The newsletter will contain a bunch of links to:
> - great civic tech projects from around the world
> - news about exciting features on those projects
> - important policy news relating to civic tech, e.g. transparency or FOI related issues
> - anything else interesting and related
> 
> Is there any kind of news that you feel you're missing at the moment? Is there anything in particular you'd like to get updates on?
> 
> The first edition will go out on the 19th February, the Thursday before the first official pub meetup for the year.
> 
> In our typically open style we're managing this project through [a public Github repo](https://github.com/openaustralia/newsletter/) where anyone can contribute links and resources to be included by [submitting an issue](https://github.com/openaustralia/newsletter/issues).
> 
> As someone in the OpenAustralia Google Group, you probably come across interesting stuff on the web all the time. Civic Tech Monthly is a great place to share discoveries with this community—people who may turn an idea into a new project or contribution.

**Comment by equivalentideas** [comment]
I think this should come from you @henare as people on that list will be more familiar with you.

**Comment by equivalentideas** [comment]
Also, I think we're ready to go with this.

**Comment by kat** [comment]
well caught Luke! Please ask if there are things that community would like to hear about and invite them to share via the information you give.  Be explicit in inviting people to contribute rather than just pointing them to a place where they can do it. This is a special group of people who have at various stages been quite active. They are also likely to have good contributions to make! :-)

**Comment by equivalentideas** [comment]
nice one @kat I've added some more about this to the draft text above. Could this be used as part of a short blog post as well?

**Comment by henare** [comment]
Thanks for the draft text @equivalentideas. That'll give me a guide but since I'm sending the email I'm rewording it quite a bit :smiley:

**Comment by equivalentideas** [comment]
:+1: :+1: :+1:

**Comment by henare** [comment]
https://groups.google.com/forum/#!topic/openaustralia-dev/bXGPWp2c1Hw
