### ISSUE TITLE
[ITEM] These women are not statistics

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#44]
http://www.theguardian.com/global/ng-interactive/2015/mar/17/these-women-are-not-statistics-deaths-in-australia-in-2015

> This is a list of women who have died in Australia this year where police have later laid charges against their partners or ex-partners.

**Comment by mlandauer** [comment]
This looks like pretty traditional journalism to me. Is there something about it to you that makes it interesting civic tech?

**Comment by equivalentideas** [comment]
> This looks like pretty traditional journalism to me. Is there something about it to you that makes it interesting civic tech?

I think it’s interesting to subscribers in it's humanising information design approach, connecting viewers to the disempowered citizen. It's also an area of much needed change in Australia and this might draw subscribers attention to a problem they might want to work on.

**Comment by kat** [comment]
I think it's too much of a leap.It looks out of place/off-topic. I'd park this one for now and look for more examples for a stronger piece on information design in civic tech in the future. Nice thought!

**Comment by equivalentideas** [comment]
> I think it's too much of a leap.It looks out of place/off-topic.

Closing this one as not included.
