### ISSUE TITLE
[ITEM] Knight News Challenge just closed

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/newsletter#46]
https://www.newschallenge.org/challenge/elections/entries?order=COMMENTS&direction=DESC

Over 1000 entries

Always lots of interesting ideas. Also quite a few submissions from Poplus people and related to Poplus components.

**Comment by henare** [comment]
> Also quite a few submissions from Poplus people and related to Poplus components.

https://www.mysociety.org/2015/03/23/a-yay-for-poplus-moment-one-bid-six-countries/

**Comment by equivalentideas** [comment]
Draft text:

The Knight News Challenge offers journalism, media and civic innovation projects a share in $3 million to realise their proposals. The latest challenge asks "How might we better inform voters and increase civic participation before, during and after elections?" There are lots of interesting ideas to inspire a project of your own.

Members of the [Poplus Federation proposed a 6 country partnership](https://www.mysociety.org/2015/03/23/a-yay-for-poplus-moment-one-bid-six-countries/) to extend [YouNextMP](http://yournextmp.com/) to Guatemala, Chile, Argentina, Peru, Scotland, and Minnesota. There's also an entry in the top 45 to [create ElectionLeaflets.org International](https://www.newschallenge.org/challenge/elections/refinement/electionleaflets-org-international).
