### ISSUE TITLE
[ITEM] NSW Pecuniary Interest Register now searchable

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#49]
http://www.theguardian.com/global/datablog/ng-interactive/2015/mar/27/search-the-nsw-register-of-pecuniary-interests-to-see-what-politicians-have-declared

**Comment by equivalentideas** [comment]
Draft Text:

## [NSW Pecuniary Interest Register now transcribed and searchable](http://www.theguardian.com/global/datablog/ng-interactive/2015/mar/27/search-the-nsw-register-of-pecuniary-interests-to-see-what-politicians-have-declared)

It’s popped up in [every edition](https://www.openaustraliafoundation.org.au/category/civic-tech-monthly/) so far, but the efforts to improve access to NSW MP’s register of interests just keep on coming. The Guardian’s call for their readers help transcribed the register forms has been answered! Nick Evershed and Todd Moore have now published the results for download and access online. Well done and thanks to everyone who got involved in the project, particularly at our [#nswvotes meetup](http://www.meetup.com/OpenAustralia-Foundation/events/219652731/) where the idea emerged.
