### ISSUE TITLE
Create mail template

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#5]

**Comment by equivalentideas** [comment]
We'll wait till we have most of the content for the first edition to do this.

**Comment by equivalentideas** [comment]
We need to start thinking about this. I'm in favour of something very clear and stripped back—both because this is a familiar, flexible (across devices) experience with email _and_ because this is the first iteration. 

I'm a fan of Web Directions super clear template for there newsletter, or just default email styles:

![screen shot 2015-02-17 at 4 16 17 pm](https://cloud.githubusercontent.com/assets/1239550/6223550/73721728-b6c0-11e4-9e0c-2c0edcaab355.png)

Does anyone else have thoughts on this? @kat @mlandauer @henare

**Comment by henare** [comment]
> I'm in favour of something very clear and stripped back

:+1:

**Comment by mlandauer** [comment]
Simple and clear sounds good to me too. A question: do we want to have the option of having images in the newsletter - putting a human face on civic tech and all that?

**Comment by equivalentideas** [comment]
I'm personally not a fan of images in emails, and my favourite newsletters don't include them—But... If we use a basic mailchimp template we'll always have that option and I'm definitely up for a relevant, useful and interesting image.

**Comment by equivalentideas** [comment]
Here's some rough ideas: cool link colour, georgia type face. I think more space between sections.

![screen shot 2015-02-18 at 8 28 40 am](https://cloud.githubusercontent.com/assets/1239550/6237587/4481714c-b748-11e4-85ad-c17ce14b3fec.png)

Anyone have good/crazy ideas for the title of the links section?

**Comment by henare** [comment]
> Anyone have good/crazy ideas for the title of the links section?

Don't have a title? :)

**Comment by equivalentideas** [comment]
> Don't have a title? :)

I think that's a good solution. I've added a line dividing the sections, the role a heading would play. I think that's helpful as it's quite a different type of text.

![screen shot 2015-02-18 at 8 36 31 pm](https://cloud.githubusercontent.com/assets/1239550/6244970/e7b8bc20-b7ad-11e4-89a8-f543b7038c20.png)

**Comment by kat** [comment]
A line says this is something else but not what it is, so I think we still need a title.

**Comment by kat** [comment]
To help create a title: What are these  and why are we including them in this newsletter?

**Comment by equivalentideas** [comment]
Going with the nautical theme of the intro do we want to carry that through and change it every month?

**Comment by kat** [comment]
does that help answer the question? style/content

**Comment by equivalentideas** [comment]
- 'Fruits of the sea'
- Civic tech links for your weekend
- Links for your weekend
- Links

**Comment by equivalentideas** [comment]
> What are these and why are we including them in this newsletter?

These are links with news, notes, thoughts, updates that will hopefully be interesting to people who are interested in civic tech.

News and Notes?

Links?

**Comment by equivalentideas** [comment]
I've put in:

> News & Notes

**Comment by equivalentideas** [comment]
Here's a final version I'm happy with for edition 1. Any final thoughts or can I close this?

![screen shot 2015-02-19 at 4 27 29 pm](https://cloud.githubusercontent.com/assets/1239550/6262276/5356cda4-b854-11e4-8a98-940386837f36.png)

**Comment by kat** [comment]
done!
