### ISSUE TITLE
[ITEM] Fantasy Frontbench

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#50]
An interesting application developed in the lead up to the UK election that uses They Work For You and Public Whip data:

http://www.fantasyfrontbench.com/

**Comment by equivalentideas** [comment]
Draft text:

An different perspective on exploring the positions and backgrounds of MPs developed in the lead up to the UK election. Fantasy Frontbench uses data from [They Work For You](http://www.theyworkforyou.com/) and [Public Whip](http://www.publicwhip.org.uk/) (equivalent of [They Vote For You](https://theyvoteforyou.org.au/) in Australia).
