### ISSUE TITLE
[ITEM] mySociety lesson plans

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#51]
...are pretty exciting https://www.mysociety.org/lesson-plans/

**Comment by equivalentideas** [comment]
Draft text:

## [Free lesson plans for civic tech and citizenship in schools](https://www.mysociety.org/lesson-plans/)

The UK’s Citizenship Foundation and mySociety have twelve lesson plans for you, including interactive activities, worksheets and background materials. The lessons aim to explain why and how students should take an active role in democracy, and how they can use civic tech tools as one way to get involved.
