### ISSUE TITLE
[ITEM] Westcon - Where do Sydney's motorists come from...?

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#58]
I think this is a really simple and powerful use of data to provide evidence to back up a position on an issue: http://minus34.com/westcon/

https://twitter.com/minus34/status/593533698957385729

By @minus34, with the source also on GitHub: https://github.com/minus34/westcon

I'll declare a conflict - I've been involved personally and unofficially in the campaign against WestConnex so before this is included in the newsletter someone else should agree it's worthy of inclusion.

**Comment by mlandauer** [comment]
As someone who knows relatively little about the issues with WestConnex I don't have a clue from looking at  http://minus34.com/westcon/ how this relates to WestConnex at all or what position it backs up.

**Comment by henare** [comment]
How interesting! What a difference a little context makes :)

I'm happy for this to be :-1: then.

**Comment by mlandauer** [comment]
It is. No doubt a sentence or two at the top of the page would make all the difference.

**Comment by minus34** [comment]
Hi Guys,

The map itself is a view of where Sydney motorists come from and where they
go to.  Hence there's no deliberate attempt to link it to WestConnex

However, when you look at the map you can see that there are few motorists
travelling from the West and South West of Sydney to the City of the
Airport.  These motorists are supposedly a significant part of the
unreleased WestConnex business case.

So, one conclusion is that the business case either doesn't stack up or
there is another agenda for building $15bn worth of tollways.  This is
where this open data becomes valuable!

Cheers,
Hugh

**Comment by henare** [comment]
Without the context this is a bit of a stretch to include so closing.
