### ISSUE TITLE
[ITEM] Free basic maths and stats course on from Knight Foundation

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#59]
http://journalismcourses.org/MJME2015.html

Having a basic grasp of maths and statistics can be extremely helpful in developing and contributing to many civic tech projects. The Knight Foundation are providing a free introductory course online June 1 - 28 to "provide journalists, media practitioners and the general public with knowledge about how to be critical about numbers, statistics and research and to avoid being improperly swayed by biased researchers."

**Comment by henare** [comment]
This feels really tenuous to me.

> Having a basic grasp of maths and statistics can be extremely helpful in developing and contributing to many civic tech projects.

Having a basic grasp of a lot of different things can be extremely helpful in developing and contributing to many civic tech projects but I don't think we'd include links to courses like this unless there's a _direct_ civic tech link.

For instance, would we include [Open University politics courses](http://www.open.edu/openlearn/society/politics-policy-people/politics)? I'm sure they'd be really useful for a budding civic hacker but without a direct link to civic tech this feels off topic to me.

So :-1: from me.

**Comment by equivalentideas** [comment]
I can see that. I do think our subscribers would be interested in the stuff about reading and being critical of research, but maybe that's just cause I'm interested in that ;-)

I'll close this.
