### ISSUE TITLE
[ITEM] Nouabook helps citizens communicate with Moroccan MPs through video

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#61]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/poplus/XWzOrY-35fI/5opG2R2OgjgJ

http://nouabook.ma/

Nouabook launched in 2014 to help citizens and Moroccan MPs communicate directly in an open forum. Andrew G. Mandelbaum, one of the project founders, explains that many Moroccans use purely spoken language and don't read, and that MPs often favour video over text based media. Responding to this context, the site now enables citizens can ask questions in video format.

This is another project built on the WriteIt Poplus component. It's interesting to see how the project can adapt to citizen needs in different contexts. Hopefully these experiences can be used to improve the project for everyone.

**Comment by henare** [comment]
Awesome.
