### ISSUE TITLE
[ITEM] When technology defines our citizenship

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#62]
https://re-publica.de/en/session/living-electromagnetic-spectrum

At the re:publica conference in Berlin earlier this month, James Bridle presents his art practice and research into government systems. He argues that the very basic assumptions of our citizenship, defined here as 'the right to rights', are changing as our governing systems adapt to the network, and that transparency alone is not enough to empower citizens to engage.

There are loads of interesting [presentations to watch](https://re-publica.de/archive/sessions) from re:publica, "Europe's biggest conference on internet and society". Let us know on if you find any gems.

**Comment by kat** [comment]
How would you feel about asking the question on social channels first and share the gems next newsletter? Can you think of a more active way to put the question? The first part feels in the right spirit (maybe mention a few key areas of interest to civic technologists) but the call to action is weak.
" There are loads of interesting [presentations to watch](https://re-publica.de/archive/sessions) from re:publica, "Europe's biggest conference on internet and society". Let us know on if you find any gems." Unless you can think of a way to lead the question in the newsletter to have the conversation on twitter/facebook first and report back?

**Comment by equivalentideas** [comment]
I included it as a more conversational thing rather than a call to action, but I like where you're going with this. I particularly like the idea of tweeting the conf and asking people to let us know what they like.

The sessions have a much deeper discussion, particularly of security and human rights, than we mostly get in Australia I think.

**Comment by kat** [comment]
Great- how about: 
There are loads of fascinating presentations to watch from re:publica, "Europe's biggest conference on internet and society". Sessions from deep discussion on security and human rights issues as well as philosophical interludes and practical application. @equivalentideas found James Bridle's art practice and research into government systems ***\* . James' work is also featured in @tacticaltech's unique and compelling documentary mini-series [link to doccos]

**Comment by mlandauer** [comment]
@kat I think that's along the right lines

**Comment by equivalentideas** [comment]
I think that's good @kat , thanks heaps for that. I'm might just change the bit about me to refer to the specific thing I found relevant so that's a bit clearer. What about:

> The [re:public conference](https://re-publica.de/en), "Europe's biggest conference on internet and society", was held in Berlin this month. There are loads of fascinating [presentations to watch](https://re-publica.de/archive/sessions) covering all kinds of topics including deep discussions on security and human rights issues as well as philosophical interludes and practical application.
> 
> Luke from the OpenAustralia Foundation found [James Bridle’s presentation](https://re-publica.de/en/session/living-electromagnetic-spectrum) particularly interesting. James argues that we’re losing our ability to access the rights and protections provided with citizenship. Governments are using algorithms to assign your citizenship status based on your communication through the internet. The rights and protections provided to you change over time, but it is extremely difficult to know where you stand. James is now working on a browser extension to help reveal this process. His work also featured in [Tactical Tech’s](https://tacticaltech.org/) compelling documentary mini-series [Exploring the Invisible](https://exposingtheinvisible.org/).

@mlandauer @kat If that's still not clear I'm happy to just drop that bit as maybe it too much to go into for these little intros :+1:

**Comment by mlandauer** [comment]
That's more specific than what was there. However, I don't actually know
what you're really saying here. What do you mean governments assign
citizenship via algorithms? Is this talking round-about about the NSA?
There, the NSA isn't assigning citizenship. They're not making someone an
American or not. They're just guessing what your citizenship is and then
applying some surveillance which might or might not be constitutional based
on that guess.

This is not clear and straightforward enough for my liking yet

**Comment by equivalentideas** [comment]
I think he’s making an argument that that is practically assigning citizenship. But I'm finding it hard to explain that in a few sentences here so why don't we leave off the James Bridle stuff and just link to the re:publica talks.

**Comment by equivalentideas** [comment]
To move this along, I'm going to cut back based on first part of what @kat added above:

### re:publica, Europe's biggest conference on internet and society

There are loads of fascinating presentations to watch from the re:publica conference, held in Berlin earlier this month. Sessions include deep discussion on security and human rights issues as well as philosophical interludes and practical application.

How about that?
