### ISSUE TITLE
[ITEM] The right to know for local communities in Kenya

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#63]
https://www.youtube.com/watch?v=eYdO17zfcXs&feature=youtu.be&a

In Kenya, Muslims for Human Rights have been working to involve citizens in the allocation of government spending in their areas. They are walking into program officers, collecting documents, taking them directly to the local people they impact, and organising forums for citizens to have there say. This 20 minute video shows their campaign for a public right to know and their social auditing process.

The question of how to make this kind of deep engagement scale online was a key theme at the recent [TICTeC conference](https://www.mysociety.org/research/tictec2015/) on the impact of civic tech. Could the approaches being used in local communities here be used in combination with online tools like [Alaveteli](http://alaveteli.org/) or [web scraping](https://morph.io/)?

We found the via the excellent [OpenParl News Brief](http://blog.openingparliament.org/post/119436788120/openparl-news-brief-may-20-2015).

**Comment by mlandauer** [comment]
The video is interesting but really doesn't have any place in the
newsletter. Asking the question how this kind of local work can scale
online is a good one and we should be linking to a discussion about that
rather than something which is essentially background knowledge to that
discussion.

**Comment by equivalentideas** [comment]
Ok cool, happy to close it if you think so.

I personally find this kind of more primary source stuff more interesting than analysis/discussion, so I can relate it to my projects/experience with tech without directly. I do think this meets what we're trying to do for subscribers:

> - connect them to other people interested in the things that they are interested in
> - reassure them of the positive impact these projects can have
> - give them interesting things to read
