### ISSUE TITLE
[ITEM] Australian budget reinstates short-term funding for Information Commissioner

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#65]
The Federal budget has re-allocated funding for the Office of Australian Information Commissioner to operate at it's reduced capacity, but the Government still plans to abolish it if it can. Here Peter Timmins describes the situation as “a step backward in the long journey towards transparent accountable government”. He's also picked out some other budget news: The [Digital Transformation Office](https://www.dto.gov.au/) has been allocated almost $100 million to establish itself over the next four years, and still no mention of the [Open Government Partnership](http://www.opengovpartnership.org/country/australia).

**Comment by kat** [comment]
I think if we're going to include these two budget factoids we could be clearer about what we're saying. It's a bit of a drift across at the moment. Are we saying this is a very mixed message on Citizen Access to Information in this year's budget"? If so we could come out and say that, including the headline. 
How about something like:

On the one hand, the Digital Transformation Office (DTO) has been allocated the $100 million startup funding to make the Australian government's front end a more rewarding experience for the citizen. Going in the opposite direction, the government has again cut funding to the  Office of the Information, and undermining its capacity to hold Government Agencies to account.  Freedom of Information (FOI) expert Peter Timmins describes the situation as “a step backward in the long journey towards transparent accountable government”.

**Comment by equivalentideas** [comment]
I really like that @kat . Do you think it's a little confusing to say funding has been cut when it's actually been added, even though it's part of a long plan to cut? :S Maybe just saying it's cutting is simplest.

**Comment by kat** [comment]
oh yes, I see what you're saying there, they haven't cut it again, quite right. It remains funded at reduced capacity.

**Comment by equivalentideas** [comment]
Maybe:

> the government has not reinstated full funding to the Office of the Information,

**Comment by kat** [comment]
How about headline "Mixed Message in Australia's Budget for Open Government"

**Comment by equivalentideas** [comment]
very nice :)

**Comment by equivalentideas** [comment]
Silly me forgot to include the actual link above http://foi-privacy.blogspot.com.au/2015/05/budget-allocates-transitional-cash-to.html
