### ISSUE TITLE
[ITEM] Launch of Hong Kong's first Freedom of Information portal

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/newsletter#68]
https://accessinfo.hk/

Powered by Alaveteli, of course ;)

**Comment by equivalentideas** [comment]
nice one :+1:

**Comment by equivalentideas** [comment]
Draft text:

> People in Hong Kong can now easily make government information requests in the open, with the launch of [Accessinfo.hk](https://accessinfo.hk). It’s powered by [Alaveteli](http://alaveteli.org/) of course, the same open source software running Australia’s [Right To Know](https://www.righttoknow.org.au/).

**Comment by equivalentideas** [comment]
I think flip around that first sentence:

> With the launch of [Accessinfo.hk](https://accessinfo.hk) people in Hong Kong can now easily make government information requests in the open. It’s powered by [Alaveteli](http://alaveteli.org/) of course, the same open source software running Australia’s [Right To Know](https://www.righttoknow.org.au/).
