### ISSUE TITLE
[ITEM] Sinar Project's "Openness and Freedom" Workshops (MY)

### ISSUE THREAD

**Issue by leowmjw** [openaustralia/newsletter#70]
Sinar Project in Malaysia has been hosting a series of online streamed workshop throughout May on the topic of Openness and Freedom; in order to raise the awareness among the local communities. 
- The first in the series focused on free culture. 
  Recorded Video link at event page --> https://plus.google.com/events/cmq8fqhjqrihfk6euqn250ro560
- The second of the series focused on Free and Open Source Software. 
  Recorded Video  --> https://www.youtube.com/watch?v=djD0b_pwhPY
- A supplementary session to the one on "Free and Open Source Software" focused on showing how to collaborate on software development, and the benefit of the opening up technical projects for non-profit. 
  Recorded Video -->  
  a) https://www.youtube.com/watch?v=EaAabrBu5BU
  b) https://www.youtube.com/watch?v=6UNx0Cq5l4Y
- Upcoming on May 30th; the final workshop in the series is about "Opening Government". This topic will be about how opening up government can help make government better. 
  Sign up to view remotely --> https://plus.google.com/events/cbt8k0f4c8gl449l4h6b89jb79s

**Comment by equivalentideas** [comment]
@leowmjw How's this in the paragraph format we're using?

> Throughout May, Malaysia's [Sinar Project](http://sinarproject.org/en) has hosted a series of [online workshops on ‘Openness and Freedom’](http://sinarproject.org/en/activities) to raise awareness in local communities. You can still catch the [final session on open government on May 30th](https://plus.google.com/events/cbt8k0f4c8gl449l4h6b89jb79s). You can watch the previous sessions on [free culture](https://www.youtube.com/watch?v=1nFcFaulr58&feature=youtu.be) and [free and open source software](https://www.youtube.com/watch?v=6UNx0Cq5l4Y) and a supplementary session in two parts on the [benefits of free software](https://www.youtube.com/watch?v=EaAabrBu5BU) and [collaborative software development](https://www.youtube.com/watch?v=djD0b_pwhPY)

**Comment by equivalentideas** [comment]
Also it would be awesome if you guys did a blog post after the events about how they went, the feedback you received and what you wanted to achieve with this approach ;)

**Comment by equivalentideas** [comment]
@leowmjw could you please give me one sentence on the outcome/response to these events?

**Comment by leowmjw** [comment]
@equivalentideas The way you have it structured is great!

**Comment by equivalentideas** [comment]
Excellent :) I think it could do with something about the response still ;)

**Comment by leowmjw** [comment]
Thanks for your feedback; we'll work on that at our next event. Here's the response ;)

"The turn out was not as expected but we were able to expose about 5 NGO activist each session on these new concepts; got 2 of them to try out new way of collaborating (using hackpad)"

**Comment by equivalentideas** [comment]
What about at the coding session? That picture at the top looks like quite a few people https://plus.google.com/events/cip9ia3dq50ag9f7daanslv0ljs

**Comment by leowmjw** [comment]
@equivalentideas That was from a much older event at the previous location of this shared space we conducted the workshop; could have been our MyMP briefing. 

The coding session (issue #71) was purely online; that had about 6 participants online.

**Comment by equivalentideas** [comment]
ok cool. Still good to transfer that knowledge directly though. I'd be interested to hear more about this another time :+1:

**Comment by leowmjw** [comment]
Sure, anytime! :+1:
