### ISSUE TITLE
[ITEM] Sinar Project's Coding Workshop Leveraging Populus Components (PopIt,MapIt)

### ISSUE THREAD

**Issue by leowmjw** [openaustralia/newsletter#71]
Khairil Yusof  from Sinar Project conducted an informal hangout to demonstrate how to develop a sample application leveraging Populus Components (PopIt,MapIt) data to find Parliamentary information given a Malaysian street address.

Recording + iPython Notebook for worked example --> https://plus.google.com/events/cip9ia3dq50ag9f7daanslv0ljs

The demo was written in Python code; systematically shows the step-by-step of using MapIT and Google Geocode web services to return enough information to do a PopIt lookup﻿for the relevant Parliamentary information.

Our entries in PopIt were sourced from the hard work of volunteers and partner online media organizations such as Malaysiakini (http://www.malaysiakini.com/) as detailed in our earlier blog posts --> http://sinarproject.org/en/updates/popit-a-key-component-for-malaysias-governance-initiatives

Our MapIt data were sourced from the hard work of volunteers from our partners TindakMalaysia (http://www.tindakmalaysia.org/).  Electoral and administrative boundary data had to be georeferenced manually (using QGIS) from the physical maps displayed in the offices of the Election Commission of Malaysia

**Comment by equivalentideas** [comment]
@leowmjw Thanks for this, I'll wrap it into an item with #70 . Maybe 'Sinar Project hosts online workshops in Openness, Freedom and civic tech development'.

**Comment by leowmjw** [comment]
sounds good @equivalentideas
