### ISSUE TITLE
[ITEM] Soft launch of Freedom of Information Portal for Malaysia

### ISSUE THREAD

**Issue by henare** [openaustralia/newsletter#91]
https://right2knowmy.wordpress.com/2015/07/30/soft-launch-of-freedom-of-information-portal-for-malaysia/

**Comment by equivalentideas** [comment]
Nice, I particularly like:

> By law, we have Freedom of Information Enactments (FOIE) in the following two states ... However, we have also added the avenue to request for information from Public Authorities not covered by FOI in order to gauge what citizens want to know at the Federal level.
