### ISSUE TITLE
[ITEM] RFC: DTO API Design Guide

### ISSUE THREAD

**Issue by maxious** [openaustralia/newsletter#93]
https://www.dto.gov.au/blog/preface-api-design-guide

**Comment by henare** [comment]
Thanks for all these links @maxious :sparkles: 

While it's obviously awesome that the Australian Government is putting stuff on GitHub, an API RFC feels a bit dry and abstract for the newsletter. Is there another angle I'm missing?

**Comment by maxious** [comment]
Bit abstract yeah, but I think there's some exciting statements like "Hard-to-use APIs create bad public policy outcomes" that could appeal to a civic tech audience... who could provide valuable feedback about how we can define good APIs. https://apiguide.readthedocs.org/en/latest/principles/index.html
(In fact some of the feedback on the blog post was to not just ask tech people about APIs because they can affect more people than just implementers)

**Comment by equivalentideas** [comment]
Hey @maxious thanks for contributing this. I decided to leave it out this time round as it was a really packed issue already (thanks to your other items :+1: ).

I think as well that there's a lot of common sense in those principles and people will be able to give some really useful feedback to the actual APIs. A post about a specific API and how it was used, or couldn't be used, in a running project could be more the type of thing for the newsletter IMHO :) But [I am often wrong about these things](https://github.com/openaustralia/newsletter/issues/44) ;-)

I'll close this.
