### ISSUE TITLE
[ITEM] OpenPlanning Launches in Hampshire, UK

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#96]
http://openplanning.hampshirehub.net/

[Hampshire Hub](http://www.hampshirehub.net/) have teamed up with [mySociety](https://www.mysociety.org/) to prototype a tool to demystify the local planning process. This is a new take on making local planning records more useful. You can read more in [Ben Nickolls blog post on the project](https://www.mysociety.org/2015/08/18/openplanning-is-making-planning-applications-more-accessible/).

In excellent open source fashion, this prototype is [forked from](https://github.com/mysociety/planningalerts-app) the OpenAustralia Foundation’s [PlanningAlerts](https://www.planningalerts.org.au), which in turn is based the UK’s original planningalerts.com. As civicpatterns.org says [“Don't Reinvent The Wheel”](http://civicpatterns.org/patterns/dont-reinvent-the-wheel/)

**Comment by henare** [comment]
Also it looks like mySociety is considering [merging back in](https://github.com/mysociety/planningalerts-app/issues/191), which would be very awesome :+1:
