### ISSUE TITLE
[ITEM] My Last Post

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#97]
https://www.mysociety.org/2015/08/07/my-last-post/

Tom has made a huge contribution to civic tech everywhere through his leadership at mySociety.

_more stuff_

We even [drew on his definition of civic tech for the focus of this newsletter](https://github.com/openaustralia/newsletter/blob/master/editions/2015-02.md).

I also love this mad post from Francis Irving ['Those brief moments when winning seems possible
'](http://www.flourish.org/2015/08/those-brief-moments-when-winning-seems-possible/) linking to Tom's post.

**Comment by henare** [comment]
:+1:
