### ISSUE TITLE
[ITEM] Yo Quiero Saber 2015

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/newsletter#98]
http://www.yoquierosaber.org/

This month Argentines got to compare the basic positions of candidates using a fun game created by Martin Szyszlican, Yas Garcia, Agustina De Luca, Adrian Pino, Ines Palacios and a team of volunteers.

Here's Martin on TV https://www.youtube.com/watch?v=9HFiV9h3M94

**Comment by henare** [comment]
Great find :+1:

**Comment by martinszy** [comment]
We also started a collective research project, at http://investigacion.yoquierosaber.org based on yournextmp.org code, here's mysociety's case study on it:
https://www.mysociety.org/about/mysociety-around-the-world/international-partners-case-study-yournextrepresentative/

**Comment by equivalentideas** [comment]
Thanks @martinszy , I missed before making the newsletter but really interesting anyway!

It's out floating out to inboxes as we speak https://twitter.com/OpenAustralia/status/634263406787194880
